-- Generated by Oracle SQL Developer REST Data Services 18.3.0.277.2354
-- Exported REST Definitions from ORDS Schema Version 18.2.0.r1831332
-- Schema: DEMO   Date: Wed Nov 14 15:30:42 CET 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'Multimedia',
      p_base_path      => '/multimedia/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Multimedia',
      p_pattern        => 'upload',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Multimedia',
      p_pattern        => 'upload',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
  multimedia_pkg.ins_blob(
    p_blob => :body
  , p_file_name => :name
  , p_mime_type => :mimetype
  , p_type => :mediatype
  );
end;'
      );


  COMMIT; 
END;